name: paypal_rest_api
description: Unofficial Dart bindings for the PayPal REST API.
version: 1.0.0-dev+1
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/paypal_dart
dependencies:
  http: ">=0.11.3 <0.12.0"
dev_dependencies:
  test: ">=0.12.13 <0.13.0"
  yaml: ">=2.0.0 <3.0.0"
