name: paypal_rest_api
description: Unofficial Dart bindings for the PayPal REST API.
version: 1.0.0-dev+2
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/paypal_dart
dependencies:
  http: ^0.12.0+4
dev_dependencies:
  test: ^1.12.0
  yaml: ^2.2.0
